# Imagem base oficial do Node.js 16
FROM node:16

# Definir o diretório de trabalho
WORKDIR /usr/src/app

# Copiar os arquivos de pacotes para o container
COPY package*.json ./

# Instalar as dependências do Node.js
RUN npm install

# Instalar as dependências do sistema necessárias para o Chromium/Google Chrome e ffmpeg em Ubuntu 24.04
RUN apt-get update && apt-get install -y \
    ffmpeg \
    fonts-liberation \
    libnss3 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libxkbcommon0 \
    libxss1 \
    xdg-utils \
    libgbm-dev \
    libasound2t64 \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Copiar o restante do código da aplicação
COPY . .

# Expor a porta
EXPOSE 3000

# Comando para rodar a aplicação
CMD ["node", "chatbot.js"]