# Imagem base oficial do Node.js LTS
FROM node:16

# Definir o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copiar package.json e package-lock.json para o container
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Instalar Google Chrome
RUN apt-get update && apt-get install -y wget unzip \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb

# Copiar o restante do código da aplicação
COPY . .

# Instalar o FFmpeg necessário para manipular mídia
RUN apt-get install -y ffmpeg

# Expor a porta utilizada pela aplicação
EXPOSE 3000

# Comando para rodar a aplicação
CMD ["node", "chatbot.js"]
